"""initial migration

Revision ID: 15e856459099
Revises: 
Create Date: 2025-05-16 11:23:19.474807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e856459099'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('chat',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_chat_id'), 'chat', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_user_id'), 'chat', ['user_id'], unique=False)
    op.create_table('deck',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deck_id')
    )
    op.create_index(op.f('ix_deck_user_id'), 'deck', ['user_id'], unique=False)
    op.create_table('quiz',
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quiz_user_id'), 'quiz', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('deck_card',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('card_with_answer', sa.Text(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_deck_card_deck_id'), 'deck_card', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_card_user_id'), 'deck_card', ['user_id'], unique=False)
    op.create_table('quiz_question',
    sa.Column('question_answer_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question_answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_answer_id')
    )
    op.create_index(op.f('ix_quiz_question_quiz_id'), 'quiz_question', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_question_user_id'), 'quiz_question', ['user_id'], unique=False)
    op.create_table('user_prompt',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_user_prompt_chat_id'), 'user_prompt', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_prompt_user_id'), 'user_prompt', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_question.question_answer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('model_response',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('model_response', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['user_prompt.query_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_model_response_chat_id'), 'model_response', ['chat_id'], unique=False)
    op.create_index(op.f('ix_model_response_query_id'), 'model_response', ['query_id'], unique=False)
    op.create_index(op.f('ix_model_response_user_id'), 'model_response', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_response_user_id'), table_name='model_response')
    op.drop_index(op.f('ix_model_response_query_id'), table_name='model_response')
    op.drop_index(op.f('ix_model_response_chat_id'), table_name='model_response')
    op.drop_table('model_response')
    op.drop_table('answers')
    op.drop_index(op.f('ix_user_prompt_user_id'), table_name='user_prompt')
    op.drop_index(op.f('ix_user_prompt_chat_id'), table_name='user_prompt')
    op.drop_table('user_prompt')
    op.drop_index(op.f('ix_quiz_question_user_id'), table_name='quiz_question')
    op.drop_index(op.f('ix_quiz_question_quiz_id'), table_name='quiz_question')
    op.drop_table('quiz_question')
    op.drop_index(op.f('ix_deck_card_user_id'), table_name='deck_card')
    op.drop_index(op.f('ix_deck_card_deck_id'), table_name='deck_card')
    op.drop_table('deck_card')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_quiz_user_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_deck_user_id'), table_name='deck')
    op.drop_table('deck')
    op.drop_index(op.f('ix_chat_user_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
