"""Relationship Issues Foreign Key

Revision ID: 1c6029835316
Revises: 531f4d8337ab
Create Date: 2025-05-18 15:28:57.407311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6029835316'
down_revision: Union[str, None] = '531f4d8337ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_tokens', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'revoked_tokens', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revoked_tokens', type_='foreignkey')
    op.drop_column('revoked_tokens', 'user_id')
    # ### end Alembic commands ###
