"""Quiz Tables Fix 1.2

Revision ID: 2d76ce95e104
Revises: 5f9f651c8a86
Create Date: 2025-06-08 01:52:59.025206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d76ce95e104'
down_revision: Union[str, None] = '5f9f651c8a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
