"""Quiz Tables Fix 1

Revision ID: 41dff864127d
Revises: 4528ed599a4b
Create Date: 2025-06-08 01:33:01.894869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dff864127d'
down_revision: Union[str, None] = '4528ed599a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quizzer_question_quiz_id_fkey', 'quizzer_question', type_='foreignkey')
    op.create_foreign_key(None, 'quizzer_question', 'quizzer', ['quiz_id'], ['quiz_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzer_question', type_='foreignkey')
    op.create_foreign_key('quizzer_question_quiz_id_fkey', 'quizzer_question', 'quiz', ['quiz_id'], ['quiz_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
