"""Quiz Tables Fix

Revision ID: 4528ed599a4b
Revises: 97c5d8956ba0
Create Date: 2025-06-08 01:23:56.860256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4528ed599a4b'
down_revision: Union[str, None] = '97c5d8956ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
