"""Flash Card Features

Revision ID: 4f7fe380de38
Revises: d98f09324b29
Create Date: 2025-05-26 12:24:56.643654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7fe380de38'
down_revision: Union[str, None] = 'd98f09324b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_attempt',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('attempt_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['deck_card.card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_flashcard_attempt_card_id'), 'flashcard_attempt', ['card_id'], unique=False)
    op.create_index(op.f('ix_flashcard_attempt_user_id'), 'flashcard_attempt', ['user_id'], unique=False)
    op.create_table('reinforced_card',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('original_card_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['deck_card.card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_card_id'], ['deck_card.card_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.add_column('deck_card', sa.Column('source_summary', sa.Text(), nullable=True))
    op.add_column('deck_card', sa.Column('source_chunk', sa.Text(), nullable=True))
    op.add_column('deck_card', sa.Column('chunk_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_card', 'chunk_index')
    op.drop_column('deck_card', 'source_chunk')
    op.drop_column('deck_card', 'source_summary')
    op.drop_table('reinforced_card')
    op.drop_index(op.f('ix_flashcard_attempt_user_id'), table_name='flashcard_attempt')
    op.drop_index(op.f('ix_flashcard_attempt_card_id'), table_name='flashcard_attempt')
    op.drop_table('flashcard_attempt')
    # ### end Alembic commands ###
