"""Quiz Tables Fix 1.1

Revision ID: 5f9f651c8a86
Revises: 41dff864127d
Create Date: 2025-06-08 01:42:19.486499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9f651c8a86'
down_revision: Union[str, None] = '41dff864127d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
