"""Task Classification

Revision ID: 75926862af9e
Revises: 2d76ce95e104
Create Date: 2025-06-16 12:56:14.664400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75926862af9e'
down_revision: Union[str, None] = '2d76ce95e104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_prompt', sa.Column('task_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_prompt', 'task_type')
    # ### end Alembic commands ###
