"""Flash Card Features Analytics

Revision ID: 945d340c5e91
Revises: 4f7fe380de38
Create Date: 2025-05-28 22:07:43.893932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945d340c5e91'
down_revision: Union[str, None] = '4f7fe380de38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_card', sa.Column('is_bookmarked', sa.Boolean(), nullable=True))
    op.add_column('deck_card', sa.Column('is_studied', sa.Boolean(), nullable=True))
    op.add_column('deck_card', sa.Column('times_reviewed', sa.Integer(), nullable=True))
    op.add_column('deck_card', sa.Column('correct_count', sa.Integer(), nullable=True))
    op.add_column('deck_card', sa.Column('wrong_count', sa.Integer(), nullable=True))
    op.add_column('deck_card', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_card', 'last_reviewed')
    op.drop_column('deck_card', 'wrong_count')
    op.drop_column('deck_card', 'correct_count')
    op.drop_column('deck_card', 'times_reviewed')
    op.drop_column('deck_card', 'is_studied')
    op.drop_column('deck_card', 'is_bookmarked')
    # ### end Alembic commands ###
